WMGeneral = """\n\nI have posted a bit about myself in the "Meet Your Faculty and Peers" thread which I encourage you to check out and add a little about yourself to. I also posted a welcome video there to familiarize yourselves with the course structure and policies.\n\nPlease see my contact information below. I encourage you to keep this information easily accessible in case you need to contact me outside of the classroom:\n\nEmail address: ashulman@email.phoenix.edu\n\nI am available in the Blackboard Ultra classroom via Messages (use the envelope icon), or via email, to offer assistance. I am usually online during the day between 9am and 5pm (Central). Faculty are required to post on five of the seven days of the week, and the days I normally post on are Tuesday, Wednesday, Thursday, Friday, and Sunday. If you are not able to access the Messages section in the classroom, please feel free email me. If there is an emergency and someone other than you needs to contact me, please have them use the above contact information to email me. No one other than you should have access to the online classroom.\n\nFor the best experience, Google Chrome is the preferred internet browser. It is recommended you periodically clear cache, cookies and history to ensure your browser is functioning at peak performance levels. If you need help with this or if you experience technical problems, please call 1-877-832-4867 for assistance. Technical Support is available to students 7 days a week from 5:00 am – 1:00 am MST.\n\nFor information regarding late assignments, please refer to the University’s standard late policy, which is outlined in the Academic Policies (see Books & Tools on our main course content page). Additionally, please remember that notes sent via Messages do not count toward attendance or participation. You must post participation within the graded discussions.\n\nIf you have any questions, please don’t hesitate to ask!\n\nSee you in class!\n\nBest,\nDrew"""


WM = {
  110: """Welcome to MTH/110: History of Mathematics. I will be your instructor for this course. This course is designed to introduce you to some of the most important mathematicians in our past and to understand how their work shaped our world today.  I look forward to working with you and am committed to your success!""",
  210: """Welcome to MTH/210: Fundamentals of Geometry. I will be your instructor for this course. I look forward to working with you and am committed to your success!\n\nThis course is designed to refresh some of your previous geometry knowledge, build new knowledge, introduce you to applications of the new and old geometry we'll learn, and improve your critical thinking skills. Along the way, we'll discuss past mathematicians and how they helped shape (no pun intended) today's geometry.""",
  217:"""Welcome to MTH/217: Statistics I. I will be your instructor for this course. I look forward to working with you and am committed to your success!\n\nThis course is an introductory journey in statistics. You will learn the foundations of statistics, with the goal of being able to critically think about data and about analyzing types of data. You are not only going to learn to think about data, but you are also going to learn how it is measured and gathered, patterns of data using measures of central tendency, and appropriate tests for using inferential statistics.""",
  218:"""Welcome to MTH/218: Statistics II. I will be your instructor for this course. I look forward to working with you and am committed to your success!\n\nThis course is a continuation on our Statistics I course. You will learn that statistics can be used in many ways, such as to disseminate information, make predictions, analyze information, and interpret data.""",
  280:"""Welcome to MTH/280: Calculus I. I will be your instructor for this course. In this course, we'lll introduce two of the fundamental pieces of calculus: limits and derivatives.  Derivatives is one of the most important tools in all of mathematics; anytime you're trying to maximize or minimize a quantity, derivatives can be used.  Finally, we'll begin the integral portion of calculus as we finish the course.  I look forward to working with you and am committed to your success!""",
  290:"""Welcome to MTH/290: Calculus II. I will be your instructor for this course. In this course, we'll continue our understanding of integrals and their applications, as well as look at seqauences and series which are useful in many mathematical courses afterwards.  Finally, we'll look into differential equations which are equations that involve derivatives and consiede why they're useful.  I look forward to working with you and am committed to your success!""",
  360: """Welcome to MTH/360: Linear Algebra I. I will be your instructor for this course. I look forward to working with you and am committed to your success!\n\nThis course is designed to introduce you to the basic concepts of linear algebra, including matrices, vectors, vector spaces, eigenvalues and eigenvectors, and linear transformations.""",    
    
}